# Generated by Django 4.2.7 on 2023-11-08 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('numero_empleado', models.IntegerField()),
                ('curp', models.CharField(max_length=18)),
                ('ssn', models.CharField(max_length=20)),
                ('numero_telefono', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('porcentaje', models.IntegerField()),
                ('curp', models.CharField(max_length=18)),
                ('ssn', models.CharField(max_length=20)),
                ('numero_telefono', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.empleado')),
            ],
        ),
    ]
