# Generated by Django 4.2.7 on 2023-11-11 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='ssn',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_empleado',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ssn',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
